config/routes.rb
Rails.application.routes.draw do
  #post 'negotiation_offers', to: 'negotiation_offers#create'
  resources :negotiation_offers
  post '/negotiations/accept/:id', to: 'negotiations#accept', as: 'accept_negotiation'
  post '/negotiations/reject/:id', to: 'negotiations#reject', as: 'reject_negotiation'
  resources :negotiations
  resources :basket_items
  resources :baskets
  get 'message/create'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :sessions => "users/sessions", :registrations => "users/registrations" }
  root 'pages#home'
  get 'users/dashboard'
  #paiement
  get '/order', to: 'orders#new'
  post '/order', to: 'orders#create'
  get '/dashboard', to: 'users#dashboard'
  get '/users/:id', to: 'users#show', as: 'users'
  get '/selling_orders', to: 'orders#selling_orders'
  get '/buying_orders', to: 'orders#buying_orders'
  get '/orders/:id', to: 'orders#show', as: "order_detail"
  get '/all_requests', to: 'requests#list'
  get '/request_offers/:id', to: 'requests#offers', as: 'request_offers'
  get '/my_offers', to: 'requests#my_offers'
  get '/search', to: 'pages#search'
  get '/calendar', to: 'pages#calendar'
  get '/plans', to: 'pages#plans'
  get '/settings/payment', to:'users#payment', as: 'settings_payment'
  get '/settings/payout', to:'users#payout', as: 'settings_payout'
  get '/gigs/:id/checkout/:pricing_type', to: 'gigs#checkout', as: 'checkout'
  get '/earnings', to: 'users#earnings', as: 'earnings'
  get '/conversations', to: 'conversations#list', as: 'conversations'
  get '/conversations/:id', to: 'conversations#show', as: 'conversation_detail'


  post 'users/edit', to: 'users#update'
  post '/offers', to: 'offers#create'
  post'/reviews', to: 'reviews#create'
  post '/settings/payment', to: 'users#update_payment', as: 'update_payment'
  post '/settings/payout', to: 'users#update_payout', as: 'update_payout'
  post '/users/withdraw', to: 'users#withdraw', as: 'withdraw'
  post '/messages', to: 'messages#create'
  post '/comments', to: 'comments#create'
  post '/subscribe', to: 'subscriptions#subscribe'
  post '/webhook', to: 'subscriptions#webhook'

  put '/orders/:id/complete', to: 'orders#complete', as: 'complete_order'
  put '/offers/:id/accept', to: 'offers#accept', as: 'accept_offer'
  put '/offers/:id/reject', to: 'offers#reject', as: 'reject_offer'

  delete '/users/remove_subscription', to: 'users#remove_subscription', as: 'remove_subscription'

   mount ActionCable.server => '/cable'

  resources :gigs do 
    member do
      delete :delete_photo
      post :upload_photo
    end
    resources :orders, only: [:create]
  end
  resources :requests
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/basket.rb
class Basket < ApplicationRecord
    has_many :basket_items, dependent: :destroy
    has_one :user

    def add_gig(gig)
        current_item = basket_items.find_by(gig_id: gig.id)

        if current_item
            current_item.increment(:quantity)
        else
            current_item = basket_items.build(gig_id: gig.id)
        end
        current_item
    end

    def total_price
        basket_items.to_a.sum { |item| item.total_price }
    end
end

app/controllers/baskets_controller.rb
class BasketsController < ApplicationController
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_basket
  before_action :set_basket, only: [:show, :edit, :update, :destroy]

  # GET /baskets
  # GET /baskets.json
  def index
    @baskets = Basket.all
  end

  # GET /baskets/1
  # GET /baskets/1.json
  def show
  end

  # GET /baskets/new
  def new
    @basket = Basket.new
  end

  # GET /baskets/1/edit
  def edit
  end

  # POST /baskets
  # POST /baskets.json
  def create
    @basket = Basket.new(basket_params)

    respond_to do |format|
      if @basket.save
        format.html { redirect_to @basket, notice: 'Basket was successfully created.' }
        format.json { render :show, status: :created, location: @basket }
      else
        format.html { render :new }
        format.json { render json: @basket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /baskets/1
  # PATCH/PUT /baskets/1.json
  def update
    respond_to do |format|
      if @basket.update(basket_params)
        format.html { redirect_to @basket, notice: 'Basket was successfully updated.' }
        format.json { render :show, status: :ok, location: @basket }
      else
        format.html { render :edit }
        format.json { render json: @basket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /baskets/1
  # DELETE /baskets/1.json
  def destroy 
    @basket.basket_items.destroy_all if @basket.id == session[:basket_id]
    #session[:basket_id] = nil
    #@basket.destroy
    respond_to do |format|
      format.html { redirect_to search_path, notice: 'Le pagner a été vidé avec succes' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_basket
      @basket = Basket.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def basket_params
      params.fetch(:basket, {})
    end

    def invalid_basket
      logger.error "Attempt to access invalid basket #{params[:id]}"
      redirect_to root_path, notice: "That basket doesn't exist"
    end
end

app/helpers/baskets_helper.rb
module BasketsHelper
end

app/views/baskets/_form.html.erb
<%= form_with(model: basket, local: true) do |form| %>
  <% if basket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(basket.errors.count, "error") %> prohibited this basket from being saved:</h2>

      <ul>
      <% basket.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/baskets/edit.html.erb
<h1>Editing Basket</h1>

<%= render 'form', basket: @basket %>

<%= link_to 'Show', @basket %> |
<%= link_to 'Back', baskets_path %>

app/views/baskets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Baskets</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @baskets.each do |basket| %>
      <tr>
        <td><%= link_to 'Show', basket %></td>
        <td><%= link_to 'Edit', edit_basket_path(basket) %></td>
        <td><%= link_to 'Destroy', basket, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Basket', new_basket_path %>

app/views/baskets/new.html.erb
<h1>New Basket</h1>

<%= render 'form', basket: @basket %>

<%= link_to 'Back', baskets_path %>

app/views/baskets/show.html.erb
<section class="section">
<div class="container">
<div class="keep-shopping pv1 mt4 has-text-right">
  <%= link_to 'Retourner au tableau de bord', dashboard_path, class: 'button is-warning' %>
</div>
<hr />
<section class="section card-template">
    <div class="basket_item_title">
        <div class="columns">
            <div class="column is-5">
                <h4>Details annonce</h4>
            </div>
            <div class="column is-3">
                 <h4 class="add_info">Quantité</h4>
            </div>
            <div class="column is-2">
                <h4>Prix</h4>
            </div>
            <div class="column is-2">
                <h4>Action</h4>
            </div>
        </div>
    </div>
    
    <%= render(@basket.basket_items) %>

<% if @basket.basket_items.count > 0 %>
  <div class="columns">
    <div class="column">
      <%= button_to 'vider le pagné', @basket, method: :delete, data: { confirm: "Etes vous sur? " }, class: "button is-danger" %>
    </div>
    <div class="column total has-text-right">
      <h4 class="title is-4">
        <span class="f5 has-text-grey">Total: </span> <%= @basket.total_price %> Fcfa
      </h4>
    </div>
  </div>
  
    <div class="columns">
        <div class="column is-2 is-offset-10">
        <%= link_to 'Commander', order_path, class: 'button is-warning' %>
        </div>
    </div>
  <% end %>
</section>
</div>
</section>