config/routes.rb
Rails.application.routes.draw do
  #post 'negotiation_offers', to: 'negotiation_offers#create'
  resources :negotiation_offers
  post '/negotiations/accept/:id', to: 'negotiations#accept', as: 'accept_negotiation'
  post '/negotiations/reject/:id', to: 'negotiations#reject', as: 'reject_negotiation'
  resources :negotiations
  resources :basket_items
  resources :baskets
  get 'message/create'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :sessions => "users/sessions", :registrations => "users/registrations" }
  root 'pages#home'
  get 'users/dashboard'
  #paiement
  get '/order', to: 'orders#new'
  post '/order', to: 'orders#create'
  get '/dashboard', to: 'users#dashboard'
  get '/users/:id', to: 'users#show', as: 'users'
  get '/selling_orders', to: 'orders#selling_orders'
  get '/buying_orders', to: 'orders#buying_orders'
  get '/orders/:id', to: 'orders#show', as: "order_detail"
  get '/all_requests', to: 'requests#list'
  get '/request_offers/:id', to: 'requests#offers', as: 'request_offers'
  get '/my_offers', to: 'requests#my_offers'
  get '/search', to: 'pages#search'
  get '/calendar', to: 'pages#calendar'
  get '/plans', to: 'pages#plans'
  get '/settings/payment', to:'users#payment', as: 'settings_payment'
  get '/settings/payout', to:'users#payout', as: 'settings_payout'
  get '/gigs/:id/checkout/:pricing_type', to: 'gigs#checkout', as: 'checkout'
  get '/earnings', to: 'users#earnings', as: 'earnings'
  get '/conversations', to: 'conversations#list', as: 'conversations'
  get '/conversations/:id', to: 'conversations#show', as: 'conversation_detail'


  post 'users/edit', to: 'users#update'
  post '/offers', to: 'offers#create'
  post'/reviews', to: 'reviews#create'
  post '/settings/payment', to: 'users#update_payment', as: 'update_payment'
  post '/settings/payout', to: 'users#update_payout', as: 'update_payout'
  post '/users/withdraw', to: 'users#withdraw', as: 'withdraw'
  post '/messages', to: 'messages#create'
  post '/comments', to: 'comments#create'
  post '/subscribe', to: 'subscriptions#subscribe'
  post '/webhook', to: 'subscriptions#webhook'

  put '/orders/:id/complete', to: 'orders#complete', as: 'complete_order'
  put '/offers/:id/accept', to: 'offers#accept', as: 'accept_offer'
  put '/offers/:id/reject', to: 'offers#reject', as: 'reject_offer'

  delete '/users/remove_subscription', to: 'users#remove_subscription', as: 'remove_subscription'

   mount ActionCable.server => '/cable'

  resources :gigs do 
    member do
      delete :delete_photo
      post :upload_photo
    end
    resources :orders, only: [:create]
  end
  resources :requests
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/basket_item.rb
class BasketItem < ApplicationRecord
  #validates :quantity, numericality: { :less_than_or_equal_to => gig.stock }

  belongs_to :gig
  belongs_to :basket

  def total_price
    self.price.to_i * quantity.to_i
  end
end

app/controllers/basket_items_controller.rb
class BasketItemsController < ApplicationController
  include CurrentBasket
  before_action :set_basket_item, only: [:show, :edit, :update, :destroy]
  before_action :set_basket, only: [:create]  

  # GET /basket_items
  # GET /basket_items.json
  def index
    @basket_items = BasketItem.all
  end

  # GET /basket_items/1
  # GET /basket_items/1.json
  def show
  end

  # GET /basket_items/new
  def new
    @basket_item = BasketItem.new
  end

  # GET /basket_items/1/edit
  def edit
  end

  # POST /basket_items
  # POST /basket_items.json
  def create
    @gig = Gig.find(params[:gig_id])
    @basket_item = @basket.add_gig(@gig)
    @basket_item.price = @gig.price

    respond_to do |format|
      if @basket_item.save
        format.html { redirect_to @basket_item.basket, notice: 'Successfully added to basket.' }
        format.json { render :show, status: :created, location: @basket_item }
      else
        format.html { render :new }
        format.json { render json: @basket_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /basket_items/1
  # PATCH/PUT /basket_items/1.json
  def update
    respond_to do |format|
      if @basket_item.update(basket_item_params)
        format.html { redirect_to @basket_item, notice: 'Basket item was successfully updated.' }
        format.json { render :show, status: :ok, location: @basket_item }
      else
        format.html { render :edit }
        format.json { render json: @basket_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /basket_items/1
  # DELETE /basket_items/1.json
  def destroy
    #@basket = Basket.find(params[:basket_id])
    @basket_item.destroy
    respond_to do |format|
      #format.html { redirect_to basket_path(@basket), notice: 'Basket item was successfully destroyed.' }
      format.html { redirect_to request.referrer, notice: 'Basket item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_basket_item
      @basket_item = BasketItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def basket_item_params
      params.require(:basket_item).permit(:gig_id, :basket_id, :quantity)
    end
end

app/helpers/basket_items_helper.rb
module BasketItemsHelper
end

app/views/basket_items/_basket_item.html.erb
<div class="columns single_item">
    <div class="column is-5">
        <article class="media">
            <figure class="media-left">
                <p class="image is-64x64">
                    <%= image_tag url_for(basket_item.gig.photos.first)%>
                </p>
            </figure>
            <div class="media-content">
                <div class="content">
                    <p>
                        <strong><%= basket_item.gig.title%></strong>
                    </p>
                </div>
            </div>
        </article>        
    </div>
    <div class="column is-3">
        <div class="select is-rounded">
            <select data-reflex="change->BasketItemReflex#incrementQuantity" data-id="<%= basket_item.id %>">
                <% for i in 1..basket_item.gig.stock do %>
                    <% if i == basket_item.quantity %>
                        <option value="<%= i %>" selected><%= i %></option>
                    <% else %>
                        <option value="<%= i %>"><%= i %></option>
                    <% end %>
                <% end %>
            </select>
        </div>
    </div>
    <div class="column is-2">
        x<%= basket_item.quantity %> <span class="tag is-rounded is-primary"> <%= basket_item.price%></span>
    </div> 
    <div class="column is-2">
        <span class="tag is-rounded is-danger"><%= link_to "Retirer du pagné", basket_item, method: :delete, data: { confirm: "Etes vous sur? " }, class:"has-text-white" %></span> 
    </div>    
</div>

app/views/basket_items/_form.html.erb
<%= form_with(model: basket_item, local: true) do |form| %>
  <% if basket_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(basket_item.errors.count, "error") %> prohibited this basket_item from being saved:</h2>

      <ul>
      <% basket_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :gig_id %>
    <%= form.text_field :gig_id %>
  </div>

  <div class="field">
    <%= form.label :basket_id %>
    <%= form.text_field :basket_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/basket_items/edit.html.erb
<h1>Editing Basket Item</h1>

<%= render 'form', basket_item: @basket_item %>

<%= link_to 'Show', @basket_item %> |
<%= link_to 'Back', basket_items_path %>

app/views/basket_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Basket Items</h1>

<table>
  <thead>
    <tr>
      <th>Gig</th>
      <th>Basket</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @basket_items.each do |basket_item| %>
      <tr>
        <td><%= basket_item.gig_id %></td>
        <td><%= basket_item.basket_id %></td>
        <td><%= link_to 'Show', basket_item %></td>
        <td><%= link_to 'Edit', edit_basket_item_path(basket_item) %></td>
        <td><%= link_to 'Destroy', basket_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Basket Item', new_basket_item_path %>

app/views/basket_items/new.html.erb
<h1>New Basket Item</h1>

<%= render 'form', basket_item: @basket_item %>

<%= link_to 'Back', basket_items_path %>

app/views/basket_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Gig:</strong>
  <%= @basket_item.gig_id %>
</p>

<p>
  <strong>Basket:</strong>
  <%= @basket_item.basket_id %>
</p>

<%= link_to 'Edit', edit_basket_item_path(@basket_item) %> |
<%= link_to 'Back', basket_items_path %>