config/routes.rb
Rails.application.routes.draw do
  #post 'negotiation_offers', to: 'negotiation_offers#create'
  resources :negotiation_offers
  post '/negotiations/accept/:id', to: 'negotiations#accept', as: 'accept_negotiation'
  post '/negotiations/reject/:id', to: 'negotiations#reject', as: 'reject_negotiation'
  resources :negotiations
  resources :basket_items
  resources :baskets
  get 'message/create'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :sessions => "users/sessions", :registrations => "users/registrations" }
  root 'pages#home'
  get 'users/dashboard'
  #paiement
  get '/order', to: 'orders#new'
  post '/order', to: 'orders#create'
  get '/dashboard', to: 'users#dashboard'
  get '/users/:id', to: 'users#show', as: 'users'
  get '/selling_orders', to: 'orders#selling_orders'
  get '/buying_orders', to: 'orders#buying_orders'
  get '/orders/:id', to: 'orders#show', as: "order_detail"
  get '/all_requests', to: 'requests#list'
  get '/request_offers/:id', to: 'requests#offers', as: 'request_offers'
  get '/my_offers', to: 'requests#my_offers'
  get '/search', to: 'pages#search'
  get '/calendar', to: 'pages#calendar'
  get '/plans', to: 'pages#plans'
  get '/settings/payment', to:'users#payment', as: 'settings_payment'
  get '/settings/payout', to:'users#payout', as: 'settings_payout'
  get '/gigs/:id/checkout/:pricing_type', to: 'gigs#checkout', as: 'checkout'
  get '/earnings', to: 'users#earnings', as: 'earnings'
  get '/conversations', to: 'conversations#list', as: 'conversations'
  get '/conversations/:id', to: 'conversations#show', as: 'conversation_detail'


  post 'users/edit', to: 'users#update'
  post '/offers', to: 'offers#create'
  post'/reviews', to: 'reviews#create'
  post '/settings/payment', to: 'users#update_payment', as: 'update_payment'
  post '/settings/payout', to: 'users#update_payout', as: 'update_payout'
  post '/users/withdraw', to: 'users#withdraw', as: 'withdraw'
  post '/messages', to: 'messages#create'
  post '/comments', to: 'comments#create'
  post '/subscribe', to: 'subscriptions#subscribe'
  post '/webhook', to: 'subscriptions#webhook'

  put '/orders/:id/complete', to: 'orders#complete', as: 'complete_order'
  put '/offers/:id/accept', to: 'offers#accept', as: 'accept_offer'
  put '/offers/:id/reject', to: 'offers#reject', as: 'reject_offer'

  delete '/users/remove_subscription', to: 'users#remove_subscription', as: 'remove_subscription'

   mount ActionCable.server => '/cable'

  resources :gigs do 
    member do
      delete :delete_photo
      post :upload_photo
    end
    resources :orders, only: [:create]
  end
  resources :requests
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_alert.html.erb
 <% unless flash.empty? %>
<script>
  <% flash.each do |key, value| %>
  <% type = key.to_s.gsub('alert', 'error').gsub('notice', 'success') %>
  new Noty ({
    type: '<%= type %>',
    layout: 'topRight',
    timeout: '3000',
    theme: 'sunset',
    text: '<%= value %>' 
     }).show();
  <% end %>
  

</script>
  
<% end %>

app/views/shared/_categories.html.erb
<nav class="navbar has-shadow" style="z-index: 5">
  <div class="container">
    <div class="navbar">
      <% @categories.each do |item| %>
      <%= link_to "#{item.name}", search_path(category: item.id), class: "navbar-item" %>
      <% end %>
    </div>
  </div>
</nav>

app/views/shared/_gigs.html.erb
<% @gigs.each do |gig| %>
    <div class="column is-one-third">
        <div class="card annonces">
            <div class="card-image">
                <%= link_to gig_path(gig) do %>
                    <figure class="image is-4by3">
                        <%= image_tag gig_cover(gig) %>
                    </figure>
                <% end %>
            </div>
            
            <div class="card-content p-t-5 p-b-5">
                <p class="subtitle is-6 m-b-5"><%= link_to gig.title.truncate(20), gig_path(gig) %></p>
                <a class="has-text-danger is-block card-footer-item has-text-right">
                    <strong><%= gig.price %> fcfa</strong>
                </a>                                      
            </div>
        </div>
    </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar header-grey" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
        <a class="navbar-item" href="/">
            <img src="/assets/logol.png" alt="Likebay ko somba pé ko téka" width="44" height="44", class="logo-img">
        </a>

        <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
        </a>
    </div>

      <div id="navbarBasicExample" class="navbar-menu">
        <div class="navbar-start">
            <div id="search-button" class="navbar-link is-arrowless" data-search data-reflex-permanent></div>
        </div>

        <div class="navbar-end">
            <%#= link_to 'Acceuil', plans_path, class: "navbar-item" %>
            <div class="navbar-item is-hoverable is-mega">
                <%#= link_to 'Categories', search_path, class: "navbar-link is-arrowless" %>
            </div>

            
            <%#= link_to 'Abonnement', plans_path, class: "navbar-item" %>
            <%= link_to 'Poster annonces', new_gig_path, class: "navbar-item" %>

            <%# if basket_has_items %>
                <%= link_to basket_path(@basket), class:"navbar-item is-warning" do %>
                    <span class="icon is-small basket-icon">
                        <i class="fa fa-shopping-cart"></i>
                    </span>
                    <span><%= basket_count_over_one %></span>
                <% end %>
            <%# end %>

            <% if (!user_signed_in?) %>
                <div class="navbar-item">
                    <div class="buttons">
                        <%= link_to  "Se connecter",  new_user_session_path, class: "button is-success" %>
                        <%= link_to  "S'enregistrer", new_user_registration_path, class: "button is-warning" %>
                    </div>
                </div>
            <% else %>
                <div class="navbar-item has-dropdown is-hoverable ">
                    <a class="navbar-link">
                        <figure class="image is-24x24 m-r-5">
                            <%= image_tag avatar_url(current_user), class: "is-rounded" %>
                        </figure>
                        <%= current_user.full_name %>
                    </a>

                    <div class="navbar-dropdown">
                        <%= link_to  "Profile", edit_user_registration_path, class: "navbar-item" %>
                        <%= link_to 'Tableau de bord', dashboard_path, class: "navbar-item" %>
                        <hr class="navbar-divider">
                        <%= link_to  "Se déconnecter", destroy_user_session_path, method: :delete, class: "navbar-item" %>
                    </div>
                </div>
            <% end %>
        </div>
    </div>
</nav>



<% if (user_signed_in?) && !current_page?(root_path) && !current_page?(plans_path) && !current_page?(search_path) && !current_page?("/gigs/#{params[:id]}") && !current_page?("/users/#{params[:id]}") %>
    <nav class="navbar has-shadow" style="z-index: 5">
        <div class="container">
            <div class="navbar">
                <%= link_to 'Tableau de bord', dashboard_path, class: "navbar-item" %>
                <%= link_to 'Commandes Ventes', selling_orders_path, class: "navbar-item" %>
                <%= link_to 'Commandes Achats', buying_orders_path, class: "navbar-item" %>
                <%= link_to 'Négotiations', negotiations_path, class: "navbar-item" %>
            </div>
        </div>

    </nav>
<% end %>


<script>
$(document).ready(function() {

  // Check for click events on the navbar burger icon
    $(".navbar-burger").click(function() {
        // Toggle the "is-active" class on both the "navbar-burger" and the "navbar-menu"
        $(".navbar-burger").toggleClass("is-active");
        $(".navbar-menu").toggleClass("is-active");
    });
});


</script>

app/views/shared/_reviews.html.erb
<% @reviews.each do |review| %>
    <div class="column is-one-quarter">
        <div class="annonces">
            <div class="card-image">
                <%= link_to gig_path(gig) do %>
                    <figure class="image is-4by3">
                        <%= image_tag gig_cover(gig) %>
                    </figure>
                <% end %>
            </div>
            <div class="card-content p-b-5">
                <div class="media">
                    <div class="media-content">
                        <p class="title is-6"><%= link_to gig.title.truncate(20), gig_path(gig) %></p>
                        <p class="subtitle is-8"><%= gig.price %> fcfa</p>
                    </div>
                </div>                                    
            </div>
        </div>
    </div>
<% end %>