config/routes.rb
Rails.application.routes.draw do
  #post 'negotiation_offers', to: 'negotiation_offers#create'
  resources :negotiation_offers
  post '/negotiations/accept/:id', to: 'negotiations#accept', as: 'accept_negotiation'
  post '/negotiations/reject/:id', to: 'negotiations#reject', as: 'reject_negotiation'
  resources :negotiations
  resources :basket_items
  resources :baskets
  get 'message/create'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :sessions => "users/sessions", :registrations => "users/registrations" }
  root 'pages#home'
  get 'users/dashboard'
  #paiement
  get '/order', to: 'orders#new'
  post '/order', to: 'orders#create'
  get '/dashboard', to: 'users#dashboard'
  get '/users/:id', to: 'users#show', as: 'users'
  get '/selling_orders', to: 'orders#selling_orders'
  get '/buying_orders', to: 'orders#buying_orders'
  get '/orders/:id', to: 'orders#show', as: "order_detail"
  get '/all_requests', to: 'requests#list'
  get '/request_offers/:id', to: 'requests#offers', as: 'request_offers'
  get '/my_offers', to: 'requests#my_offers'
  get '/search', to: 'pages#search'
  get '/calendar', to: 'pages#calendar'
  get '/plans', to: 'pages#plans'
  get '/settings/payment', to:'users#payment', as: 'settings_payment'
  get '/settings/payout', to:'users#payout', as: 'settings_payout'
  get '/gigs/:id/checkout/:pricing_type', to: 'gigs#checkout', as: 'checkout'
  get '/earnings', to: 'users#earnings', as: 'earnings'
  get '/conversations', to: 'conversations#list', as: 'conversations'
  get '/conversations/:id', to: 'conversations#show', as: 'conversation_detail'


  post 'users/edit', to: 'users#update'
  post '/offers', to: 'offers#create'
  post'/reviews', to: 'reviews#create'
  post '/settings/payment', to: 'users#update_payment', as: 'update_payment'
  post '/settings/payout', to: 'users#update_payout', as: 'update_payout'
  post '/users/withdraw', to: 'users#withdraw', as: 'withdraw'
  post '/messages', to: 'messages#create'
  post '/comments', to: 'comments#create'
  post '/subscribe', to: 'subscriptions#subscribe'
  post '/webhook', to: 'subscriptions#webhook'

  put '/orders/:id/complete', to: 'orders#complete', as: 'complete_order'
  put '/offers/:id/accept', to: 'offers#accept', as: 'accept_offer'
  put '/offers/:id/reject', to: 'offers#reject', as: 'reject_offer'

  delete '/users/remove_subscription', to: 'users#remove_subscription', as: 'remove_subscription'

   mount ActionCable.server => '/cable'

  resources :gigs do 
    member do
      delete :delete_photo
      post :upload_photo
    end
    resources :orders, only: [:create]
  end
  resources :requests
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :user
  belongs_to :category

  has_one_attached :attachment_file
  has_many :offers, dependent: :delete_all
  has_many :orders

  validates :title, presence: {message: "Ne peut pas être vide"}
  validates :description, presence: {message: "Ne peut pas être vide"}
  validates :delivery, numericality: {only_integer: true, message:  "Doit être un chiffre"}


end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_request, except: [:new, :create, :index, :list, :my_offers]
  before_action :is_authorized, only: [:edit, :update, :destroy, :offers]
  before_action :set_categories, only: [:new, :edit, :list]


  def index
    @requests = current_user.requests
  end

  def new
    @request = current_user.requests.build
  end

  def create
       @request = current_user.requests.build(request_params)
       if @request.save
        redirect_to requests_path, notice: "Saved..."
      else
        redirect_to request.referrer, flash: {error: @request.errors.full_messages.join('. ')}
      end
  end

  def update
    if @request.update(request_params)
    redirect_to requests_path, notice: "Saved..."
    else
    redirect_to request.referrer, flash: {error: @request.errors.full_messages.join('. ')}
    end
  end

  def show
  end

  def edit

  end

  def destroy
    @request.destroy
    redirect_to requests_path, notice: "Deleted"
  end

  def list
    @category_id = params[:category]
    if @category_id.present?
      @requests = Request.where(category_id: @category_id)
      else
      @requests = Request.all
    end
  end

  def offers
    @offers = @request.offers

  end

  def my_offers
    @offers = current_user.offers
  end

  private

  def set_categories
    @categories = Category.all
  end

  def set_request
    @request = Request.find(params[:id])
  end

  def is_authorized
    redirect_to root_path, alert: "You don't have permission" unless current_user.id == @request.user_id
  end



  def request_params
     params.require(:request).permit(:description, :category_id, :delivery, :budget, :attachment_file, :title)
    end
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/requests/edit.html.erb
<section class="section">
  <div class="container">
  <div class="form-container">
    <p class="title is-4 has-text-centered">What Services Are You Looking For</p>
    <%= form_for @request do |f| %>
      <div class="field">
        <label class="label">Title (*)</label>
        <%= f.text_field :title, placeholder: "I request....", class: "input" %>
      </div>
      <div class="field">
        <label class="label">Description (*)</label>
        <%= f.text_area :description, placeholder: "I'm looking for....", class: "textarea" %>
      </div>

      <div class="field">
        <label class="label">Choose a category</label>
        <div class="select is-fullwidth">
          <%= f.select(:category_id, options_for_select(@categories.map { |c| [c.name, c.id] }, selected: @request.category_id)) %>
        </div>
      </div>

      <div class="field">
        <label class="label">Delivery</label>
        <%= f.number_field :delivery, placeholder: "1-30 days", class: "input" %>
      </div>


      <div class="field">
        <label class="label">Budget</label>
        <%= f.number_field :budget, placeholder: "$5 minimum", class: "input" %>
      </div>

      <div class="field">
        <label class="label">Upload attachment (Optional)</label>
        <div class="
        file is-warning has-name">
        <label class="file-label">
          <%= f.file_field :attachment_file, class: "file-input" %>
          <span class="file-cta"><span class="file-label">Choose a file...</span></span>
          <span class="file-name" id="file_name">No file selected</span>
        </label>
      </div>
    </div>

     <% if @request.attachment_file.attached? %>
     <p>
      <%= link_to url_for(@request.attachment_file), class: "tag small is-warning m-t-20",
      download: "Attachment_#{@request.attachment_file.id}" do %>
      <i class="fas fa-paperclip fa-lg p-r-5"></i> <%= @request.attachment_file.filename %>

      <% end %> 
     </p>

     <% end %>
    <div class="field has-text-centered">
      <%= f.submit 'Update request', class: 'button is-primary' %>
      </div>
    <% end %>
  </div>
</div>
</section>

<script>
  $(document).ready(function() {
    var file = $('.file-input');
    file.change(function(e) {
      if (file[0].files.length > 0) {
        var attachment = file[0].files[0];
        $('.file-name').text(attachment.name + " (" + attachment.size + "bytes)");
      }
    })
  })
</script>

app/views/requests/index.html.erb
<section class="section">
  <div class="container">
    <p class="title">

      <p class="title">
       Gérer les demandes

        <%= link_to 'Publier une nouvelle demande', new_request_path, class: "button is-primary is-pulled-right" %>
      </p>

      <table class="table is-fullwidth">
        <thead class="is-centered">
          <tr>

            <td>Date</td>
            <td>Demande</td>
            <td class="has-text-right">Offres</td>
            <td class="has-text-right">Action</td>
          </tr>
          </thead>
          <tbody>

            <% if @requests.blank? %>
            <tr>
              <td colspan="4" class="has-text-centered"><h1>RIEN A MONTRER PAR ICI</h1></td>
            </tr>
            <% end %>
            <% @requests.each do |r| %>
            <tr>

              <td><%= r.created_at.strftime('%d, %b %Y') %></td>
              <td><%= link_to r.title, request_path(r) %></td>
              <td class="has-text-right">
                <%= link_to r.offers.count, request_offers_path(r) %>
              </td>
            <td class="has-text-right">
              <%= link_to edit_request_path(r), class: "m-r-5" do %>
              <span class="icon has-text-success">
                <i class="far fa-edit fa-lg"></i>
              </span>
              <% end %>

              <%= link_to r, method: :delete, data: {confirm: "Are you sure"} do %>
              <span class="icon has-text-danger">
               <i class="far fa-trash-alt fa-lg"></i>
             </span>
             <% end %>
            </td>
            </tr>
            <% end %>
          </tbody>
        </table>


  </section>

app/views/requests/list.html.erb
<section class="section">
  <div class="container">
    <p class="title">
      Toutes les demandes

     <%= link_to "Publier une demande", new_request_path, class: "button is-primary is-pulled-right" %>

    </p>
    <div class="card">
      <div class="card-header">
        <%= form_tag '', method: :get do %>

        <div class="field p-10">
          <div class="select">
            <%= select_tag 'category', content_tag(:option, 'Toutes les categories', value: "") + options_for_select(@categories.map { |c| [c.name, c.id ]}, selected: @category_id), onchange: "this.form.submit();" %>

          </div>
        </div>

        <% end %>

      </div>
      <div class="card-content">
        <table class="table is-fullwidth">
          <thead>
            <tr>
              <th>Date</th>
               <th>Acheteur</th>
                <th>Demandes</th>
                <th class="has-text-centered">Offres</th>
               <th class="has-text-centered">Durée</th>
              <th class="has-text-centered">Budget</th>
            </tr>
          </thead>
          <tbody>
               <% if @requests.blank? %>
            <tr>
              <td colspan="6" class="has-text-centered"><h1>RIEN A MONTRER PAR ICI</h1></td>
            </tr>
            <% end %>
            <% @requests.each do |r| %>
            <tr>
               <td><%= r.created_at.strftime('%d, %b, %Y')%></td>
               <td>
                 <figure class="image is-48x48">
                  <%= image_tag avatar_url(r.user), class: "is-rounded" %>
                </figure>
               </td>
                <td>
                  <%= link_to request_path(r), class: "tooltip" do %>
                  <label for="" class="tooltip" data-tooltip="<%= r.description %>">
                    <%= r.title.truncate(25, seperator: ' ') %>
                  </label>
                  <% end %>

                </td>
                 <td class="has-text-right"><%= r.offers.count %></td>
               <td class="has-text-right"><%= pluralize(r.delivery, 'day') %></td>
               <td class="has-text-right"><%= r.budget %></td>
             </tr>
             <% end %>
             </tbody>

        </table>

     
      </div>

    </div>




  </div>
  

</section>

app/views/requests/my_offers.html.erb
<section class="section">
  <div class="container">
 <p class="title">My Offers</p>
 <table class="table is-fullwidth">
  <thead>
    <tr>

      <th>Date</th>
      <th>Request Title</th>
      <th>Budget</th>
      <th>Offer Amount</th>
      <th>Deliver in</th>
      <th>Status</th>
    </tr>
  </thead>
  <tbody>
    <% if @offers.blank? %>
    <tr>
      <td colspan="6" class="has-text-centered"><h1>Nothing to Show Here</h1></td>
    </tr>
    <% end %>
    <% @offers.each do |o| %>
    <tr>

      <td><%= o.created_at.strftime(' %d, %b %Y' ) %></td>
       <td>
        <%= link_to o.request.title, request_path(o.request) %>
       </td>
        <td>$<%= o.request.budget %></td>
       <td>$<%= o.amount %></td>
        <td><%= pluralize(o.days, 'day') %></td>
         <td><%= o.status.capitalize %></td>
          <td>
           <span class="tag <%=  'is-warning' if o.pending? %>
            <%=  'is-success' if o.pending? %>
            <%=  'is-danger' if o.pending? %>">
            <%= o.status.capitalize %>
          </span>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>
</section>

app/views/requests/new.html.erb
<section class="section">
  <div class="container">
  <div class="form-container">
    <p class="title is-4 has-text-centered">Quelle produit recherché vous ?</p>
    <%= form_for @request do |f| %>
      <div class="field">
        <label class="label">Nom</label>
        <%= f.text_field :title, placeholder: "Je cherches....", class: "input" %>
      </div>
      <div class="field">
        <label class="label">Description</label>
        <%= f.text_area :description, placeholder: "Ajoutez des détails....", class: "textarea" %>
      </div>

      <div class="field">
        <label class="label">Choisissez une categorie</label>
        <div class="select is-fullwidth">
          <%= f.select(:category_id, options_for_select(@categories.map { |c| [c.name, c.id] })) %>
        </div>
      </div>

      <div class="field">
        <label class="label">Livrable</label>
        <%= f.number_field :delivery, placeholder: "1-30 jours", class: "input" %>
      </div>


      <div class="field">
        <label class="label">Budget</label>
        <%= f.number_field :budget, placeholder: "12000 minimum", class: "input" %>
      </div>

      <div class="field">
        <label class="label">Attachez un fichier (Optionelle)</label>
        <div class="
        file is-warning has-name">
        <label class="file-label">
          <%= f.file_field :attachment_file, class: "file-input" %>
          <span class="file-cta"><span class="file-label">Choisissez un fichier...</span></span>
          <span class="file-name" id="file_name">Aucun fichier sélectionné</span>
        </label>
      </div>
    </div>
    <div class="field has-text-centered">
      <%= f.submit 'Poster votre requette', class: 'button is-primary' %>
      </div>
    <% end %>
  </div>
</div>
</section>

<script>
  $(document).ready(function() {
    var file = $('.file-input');
    file.change(function(e) {
      if (file[0].files.length > 0) {
        var attachment = file[0].files[0];
        $('.file-name').text(attachment.name + " (" + attachment.size + "bytes)");
      }
    })
  })
</script>

app/views/requests/offers.html.erb
<section class="section">
  <div class="container">
 <p class="title">View Offers</p>
 <table class="table is-fullwidth">
  <thead>
    <tr>

      <th>Date</th>
      <th>Seller Name</th>
      <th>Notes</th>
      <th>Amount</th>
      <th>Deliver in</th>
      <th>Status</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
    <% if @offers.blank? %>
    <tr>
      <td colspan="7" class="has-text-centered"><h1>Nothing to Show Here</h1></td>
    </tr>
    <% end %>
    <% @offers.each do |o| %>
    <tr>

      <td><%= o.created_at.strftime(' %d, %b %Y' ) %></td>
       <td>
         <figure class="image is-48x48">
          <%= image_tag avatar_url(o.user), class: "is-rounded" %>
        </figure>
       </td>
        <span class="tag <%=  'is-warning' if o.pending? %>
            <%=  'is-success' if o.pending? %>
            <%=  'is-danger' if o.pending? %>">
            <%= o.status.capitalize %>
          </span>
        </td>
          <td>
            <%= link_to accept_offer_path(o), method: :put,
            data: { confirm: "Are you sure?" },
             class: "button is-small is-primary is outlined #{'is-hidden' if !o.pending?}" do %> 
             <span class="icon"><i class="far fa-check-circle fa-lg"></i></span>
             <span>Accept</span>
            <% end %>
              <%= link_to reject_offer_path(o), method: :put,
            data: { confirm: "Are you sure?" },
             class: "button is-small is-danger is outlined #{'is-hidden' if !o.pending?}" do %> 
             <span class="icon"><i class="far fa-time-circle fa-lg"></i></span>
             <span>Reject</span>
            <% end %>

        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>
</section>

app/views/requests/show.html.erb
<section class="section">
    <div class="container">
        <div class="columns">

            <!-- LEFT SIDE -->
            <div class="column is-two-thirds">
                <div class="columns is-multiline">

                    <!-- Title -->
                    <div class="column is-full">
                         <p class="title is-4"><%= @request.title %></p>
                        <article class="media">
                            <div class="media-content">
                <p>
                    <%= @request.category.name %>
                    <span class="is-pulled-right">Posté le: <%= @request.created_at.strftime('%d, %b %Y') %>
                                </p>
                                Besoin d'être livré en: <%= @request.delivery %> days | Offres: <%= @request.offers.count %>| Budget: $<%= @request.budget %>
                            </div>
                        </article>
                        
                        
                    </div>

                    <!-- Description -->
                    <div class="column is-full">
                        <div class="card">
                            <div class="card-content">
                            <strong>Description</strong>
                            <hr>
                            <%= @request.description %>
                            <% if @request.attachment_file.attached? %>
                            <p>
                                <%= link_to url_for(@request.attachment_file),
                                class: "tag small is-warning m-t-20",
                                    download: "Attachment_#{@request.attachment_file.id}" do %>
                                    <i class="fas fa-paperclip fa-lg p-r-5"></i><%= @request.attachment_file.filename %>
                                    <% end %>
                                </p>
                                <% end %>
                            </div>
                        </div>

                    </div>

                    <!-- About Buyer -->
                    <div class="column">
                        <div class="card">
                            <div class="card-content">
                                <strong>À propos de l'acheteur</strong> 
                                <hr/>

                                <div class="content">
                                    <div class="columns">

                                        <!-- Buyer Avatar -->
                                        <div class="column">
                                            <div class="card-content is-horizontal-center is-flex">
                                                <figure class="image is-96x96">
                                                    <%= image_tag avatar_url(@request.user), class: "is-rounded" %>
                                            </figure>
                                        </div>

                                        <div class="content has-text-centered">
                                            <p class="title is-5"><%= @request.user.full_name %></p>
                                        </div>

                                            
                                        </div>

                                        <!-- Buyer Profile -->
                                        <div class="column f-15">
                                             <article class="media">
                                              <div class="media-content">
                                                <i class="fas fa-user m-r-5"></i>Membre depuis</div>

                                              <div class="media-right">
                                                <%= @request.user.created_at.strftime('%b %Y') %>

                                              </div>
                                            </article>
                                                <article class="media">
                                              <div class="media-content">
                                                <i class="fas fa-map-marker-alt m-r-5"></i>De</div>

                                              <div class="media-right">
                                                <%= @request.user.from %>

                                              </div>
                                            </article>
                                                <article class="media">
                                              <div class="media-content">
                                               <%= @request.user.about %>
                                              </div>
                                            </article>
                                            
                                        </div>

                                    </div>
                                </div>

                                    
                            </div>
                        </div>
                    </div>
                    
                </div>
            </div>

            <!-- RIGHT SIDE -->
            <div class="column">
                <div class="card">
                    <%= form_for Offer.new do |f| %>
                    <div class="card-content">
                        <%= f.hidden_field :request_id, value: @request.id %>
                        <div class="field">
                            <label for="" class="
                            label">Prix (FCFA)</label>
                            <%= f.text_field :amount, class: "input" %>
                        </div>
                         <div class="field">
                            <label for="" class="
                            label">Livrer en (jours)</label>
                            <%= f.text_field :days, class: "input" %>
                        </div>
                        <%= f.submit 'Faire un offre', class: "button is-primary is-fullwidth" %>

                    </div>

                    <% end %>



              </div>
                
            </div>

        </div>
    </div>
</section>